### ISSUE TITLE
SSL error on demo server

### ISSUE THREAD

**Issue by engn33r** [mvexel/openstreetmap-vintage-tile-server#4]
When I click the README link to visit https://osm.lol, I encounter a Cloudflare Invalid SSL Certificate error (cloudflare error code 526)

**Comment by mvexel** [comment]
fixed! I hope!

**Comment by engn33r** [comment]
@mvexel unfortunately I still see the error

![Image](https://github.com/user-attachments/assets/54df95c2-5e76-4b9b-b577-08002c8b3c3f)
